name: Wechat

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: WeChat Robot message
      run: curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0a247bf0-778f-471d-9bf1-515c0d926ad0'
